version: '3.1'

services:
  mysql:
    image: mysql:5.6.41
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - sql:/var/lib/mysql
  api:
    build:
      dockerfile: normal.Dockerfile
      context: .
      args:
        APP_ENV: ${APP_ENV}
    container_name: api
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - ./:/todos
      - /todos/vendor
    environment:
      DB: "root:password@tcp(mysql:3306)/database"
      GO111MODULE: "on"
volumes:
  sql: